# WinBoat Guest Server
# Instead of querying the locale dependent quser.exe,
# we use directly the Win32 API through Powershell.
# This is a more robust approach than parsing quser.exe
# and more importantly locale independent!

# The function will query Win32 API for sessions.
# We call the function and filter by state (active) and type (RDP),
# if there are any sessions a simple 1 will be printed,
# otherwise a 0 will be printed.

# The following function and description has been generated by AI.
<#
.SYNOPSIS
    Retrieves detailed information about active and disconnected sessions on local or remote computers using the Windows Terminal Services API.

.DESCRIPTION
    The Get-WTSSession function uses the native Windows Terminal Services API (wtsapi32.dll) via P/Invoke to enumerate user sessions.
    It provides structured output including Session ID, Username, Session State (Active/Disconnected), and Connection Type (Console, RDP, or Citrix).

    Unlike parsing the output of `quser` or `query user`, this function is completely language-independent and more reliable across different Windows versions and configurations.

.PARAMETER ComputerName
    Specifies the name of the computer(s) to query. Defaults to the local computer if not specified.
    Accepts pipeline input and multiple computer names.

.OUTPUTS
    PSCustomObject
    Returns objects with the following properties:
    - ComputerName
    - SessionId
    - StationName
    - UserName
    - State (numeric)
    - StateName (Active / Disconnected)
    - IsActive (boolean)
    - ConnectionType (Console / RDP / Citrix ICA / Other)

.EXAMPLE
    Get-WTSSession

    Lists all sessions on the local computer.

.EXAMPLE
    Get-WTSSession -ComputerName "SERVER01", "SERVER02"

    Queries sessions on two remote servers.

.EXAMPLE
    Get-WTSSession | Where-Object IsActive | Format-Table

    Shows only currently active sessions in a table.

.EXAMPLE
    "PC01","PC02" | Get-WTSSession | Export-Csv -Path "Sessions.csv" -NoTypeInformation

    Exports session information from multiple computers to a CSV file.

.NOTES
    - Requires appropriate permissions (usually local administrator rights on the target computer).
    - Works on Windows 10/11 and Windows Server 2012 R2 and newer.
    - This function is more robust and language-independent than using `quser.exe`.
    - Memory is properly cleaned up using WTSFreeMemory.

.LINK
    https://learn.microsoft.com/en-us/windows/win32/api/wtsapi32/
#>
function Get-WTSSession {
    [CmdletBinding()]
    param(
        [string]$ComputerName = $env:COMPUTERNAME
    )

    $Signature = @"
using System;
using System.Runtime.InteropServices;

public class WTS {
    [DllImport("wtsapi32.dll", SetLastError = true)]
    public static extern bool WTSEnumerateSessions(IntPtr hServer, int Reserved, int Version, 
        ref IntPtr ppSessionInfo, ref int pCount);

    [DllImport("wtsapi32.dll", SetLastError = true)]
    public static extern bool WTSQuerySessionInformation(IntPtr hServer, int SessionId, 
        int WTSInfoClass, out IntPtr ppBuffer, out int pBytesReturned);

    [DllImport("wtsapi32.dll")]
    public static extern void WTSFreeMemory(IntPtr pMemory);

    [DllImport("wtsapi32.dll", SetLastError = true)]
    public static extern IntPtr WTSOpenServer([MarshalAs(UnmanagedType.LPWStr)] string pServerName);

    [DllImport("wtsapi32.dll")]
    public static extern void WTSCloseServer(IntPtr hServer);

    [StructLayout(LayoutKind.Sequential)]
    public struct WTS_SESSION_INFO {
        public int SessionId;
        [MarshalAs(UnmanagedType.LPWStr)] public string pWinStationName;
        public int State;
    }
}
"@

    if (-not ([System.Management.Automation.PSTypeName]'WTS').Type) {
        Add-Type -TypeDefinition $Signature -ErrorAction Stop
    }

    $hServer = if ($ComputerName -eq $env:COMPUTERNAME) { 
        [IntPtr]::Zero 
    } else { 
        [WTS]::WTSOpenServer($ComputerName) 
    }

    try {
        $SessionInfoPtr = [IntPtr]::Zero
        $Count = 0

        $success = [WTS]::WTSEnumerateSessions($hServer, 0, 1, [ref]$SessionInfoPtr, [ref]$Count)
        if (-not $success) {
            Write-Error "Konnte Sessions nicht abfragen auf $ComputerName"
            return
        }

        $ElementSize = [System.Runtime.InteropServices.Marshal]::SizeOf([type][WTS+WTS_SESSION_INFO])
        $CurrentPtr = $SessionInfoPtr

        for ($i = 0; $i -lt $Count; $i++) {
            $session = [System.Runtime.InteropServices.Marshal]::PtrToStructure($CurrentPtr, [type][WTS+WTS_SESSION_INFO])

            # === Benutzername (InfoClass 5) - ANSI Version, weil sie bei dir funktioniert ===
            $userBuffer = [IntPtr]::Zero
            $bytesReturned = 0
            $userName = $null

            if ([WTS]::WTSQuerySessionInformation($hServer, $session.SessionId, 5, [ref]$userBuffer, [ref]$bytesReturned)) {
                if ($bytesReturned -gt 0) {
                    $userName = [System.Runtime.InteropServices.Marshal]::PtrToStringAnsi($userBuffer)
                }
                [WTS]::WTSFreeMemory($userBuffer)
            }

            # === Protokoll-Typ (InfoClass 16) ===
            $protoBuffer = [IntPtr]::Zero
            $protoBytes = 0
            $protocol = "Unknown"

            if ([WTS]::WTSQuerySessionInformation($hServer, $session.SessionId, 16, [ref]$protoBuffer, [ref]$protoBytes)) {
                $code = [System.Runtime.InteropServices.Marshal]::ReadInt16($protoBuffer)
                [WTS]::WTSFreeMemory($protoBuffer)

                $protocol = switch ($code) {
                    0 { "Console" }
                    1 { "Citrix ICA" }
                    2 { "RDP" }
                    default { "Other ($code)" }
                }
            }

            if (-not [string]::IsNullOrWhiteSpace($userName)) {
                [PSCustomObject]@{
                    ComputerName   = $ComputerName
                    SessionId      = $session.SessionId
                    StationName    = $session.pWinStationName
                    UserName       = $userName
                    State          = $session.State
                    StateName      = if ($session.State -eq 0) { "Active" } else { "Disconnected" }
                    IsActive       = $session.State -eq 0
                    ConnectionType = $protocol
                }
            }

            $CurrentPtr = [IntPtr]($CurrentPtr.ToInt64() + $ElementSize)
        }
    }
    finally {
        if ($SessionInfoPtr -ne [IntPtr]::Zero) {
            [WTS]::WTSFreeMemory($SessionInfoPtr)
        }
        if ($hServer -ne [IntPtr]::Zero -and $ComputerName -ne $env:COMPUTERNAME) {
            [WTS]::WTSCloseServer($hServer)
        }
    }
}

if (Get-WTSSession | Where-Object { $_.IsActive } | Where-Object { $_.ConnectionType -match 'RDP' }) {'1'} else {'0'}
