# WinBoat Guest Server
# Instead of querying the locale dependent quser.exe,
# we use directly the Win32 API through Powershell.
# This is a more robust approach than parsing quser.exe
# and more importantly locale independent!

# The function will query Win32 API for sessions.
# The functions filter by state (active) and type (RDP)
# and returns a boolean if there is at least one session.
# If there are any sessions a simple 1 will be printed,
# otherwise a 0 will be printed.

# The following function and description has been generated by AI.
<#
.SYNOPSIS
    Returns $true if an active RDP session exists on the specified computer.

.DESCRIPTION
    Uses the Windows Terminal Services API to check for active RDP sessions.
    Returns immediately upon finding the first active RDP session.

.PARAMETER ComputerName
    Target computer name. Defaults to localhost.

.OUTPUTS
    Boolean
#>
function Has-RDP-Session {
    [CmdletBinding()]
    param(
        [string]$ComputerName = $env:COMPUTERNAME
    )

    $Signature = @"
using System;
using System.Runtime.InteropServices;

public class WTS {
    [DllImport("wtsapi32.dll", SetLastError = true)]
    public static extern bool WTSEnumerateSessions(IntPtr hServer, int Reserved, int Version, 
        ref IntPtr ppSessionInfo, ref int pCount);

    [DllImport("wtsapi32.dll", SetLastError = true)]
    public static extern bool WTSQuerySessionInformation(IntPtr hServer, int SessionId, 
        int WTSInfoClass, out IntPtr ppBuffer, out int pBytesReturned);

    [DllImport("wtsapi32.dll")]
    public static extern void WTSFreeMemory(IntPtr pMemory);

    [DllImport("wtsapi32.dll", SetLastError = true)]
    public static extern IntPtr WTSOpenServer([MarshalAs(UnmanagedType.LPWStr)] string pServerName);

    [DllImport("wtsapi32.dll")]
    public static extern void WTSCloseServer(IntPtr hServer);

    [StructLayout(LayoutKind.Sequential)]
    public struct WTS_SESSION_INFO {
        public int SessionId;
        [MarshalAs(UnmanagedType.LPWStr)] public string pWinStationName;
        public int State;
    }
}
"@

    if (-not ([System.Management.Automation.PSTypeName]'WTS').Type) {
        Add-Type -TypeDefinition $Signature -ErrorAction Stop
    }

    $hServer = if ($ComputerName -eq $env:COMPUTERNAME) { 
        [IntPtr]::Zero 
    } else { 
        [WTS]::WTSOpenServer($ComputerName) 
    }

    try {
        $SessionInfoPtr = [IntPtr]::Zero
        $Count = 0

        $success = [WTS]::WTSEnumerateSessions($hServer, 0, 1, [ref]$SessionInfoPtr, [ref]$Count)
        if (-not $success) {
            Write-Error "Konnte Sessions nicht abfragen auf $ComputerName"
            return $false
        }

        $ElementSize = [System.Runtime.InteropServices.Marshal]::SizeOf([type][WTS+WTS_SESSION_INFO])
        $CurrentPtr = $SessionInfoPtr

        for ($i = 0; $i -lt $Count; $i++) {
            $session = [System.Runtime.InteropServices.Marshal]::PtrToStructure($CurrentPtr, [type][WTS+WTS_SESSION_INFO])

            # Nur aktive Sessions prüfen (State = 0)
            if ($session.State -eq 0) {
                
                # Protokoll-Typ abfragen (InfoClass 16)
                $protoBuffer = [IntPtr]::Zero
                $protoBytes = 0
                $isRDP = $false

                if ([WTS]::WTSQuerySessionInformation($hServer, $session.SessionId, 16, [ref]$protoBuffer, [ref]$protoBytes)) {
                    $code = [System.Runtime.InteropServices.Marshal]::ReadInt16($protoBuffer)
                    [WTS]::WTSFreeMemory($protoBuffer)

                    if ($code -eq 2) {
                        # RDP gefunden + aktiv → sofort beenden
                        return $true
                    }
                }
            }

            $CurrentPtr = [IntPtr]($CurrentPtr.ToInt64() + $ElementSize)
        }

        # Keine aktive RDP-Session gefunden
        return $false

    }
    finally {
        if ($SessionInfoPtr -ne [IntPtr]::Zero) {
            [WTS]::WTSFreeMemory($SessionInfoPtr)
        }
        if ($hServer -ne [IntPtr]::Zero -and $ComputerName -ne $env:COMPUTERNAME) {
            [WTS]::WTSCloseServer($hServer)
        }
    }
}

if (Has-RDP-Session) {'1'} else {'0'}
