// The following code has been generated by AI.

using System;
using System.Runtime.InteropServices;

public static class WtsSessionChecker
{
    [DllImport("wtsapi32.dll", SetLastError = true)]
    private static extern bool WTSEnumerateSessions(IntPtr hServer, int Reserved, int Version, 
        ref IntPtr ppSessionInfo, ref int pCount);

    [DllImport("wtsapi32.dll", SetLastError = true)]
    private static extern bool WTSQuerySessionInformation(IntPtr hServer, int SessionId, 
        int WTSInfoClass, out IntPtr ppBuffer, out int pBytesReturned);

    [DllImport("wtsapi32.dll")]
    private static extern void WTSFreeMemory(IntPtr pMemory);

    [DllImport("wtsapi32.dll", SetLastError = true)]
    private static extern IntPtr WTSOpenServer([MarshalAs(UnmanagedType.LPWStr)] string pServerName);

    [DllImport("wtsapi32.dll")]
    private static extern void WTSCloseServer(IntPtr hServer);

    [StructLayout(LayoutKind.Sequential)]
    private struct WTS_SESSION_INFO
    {
        public int SessionId;
        public IntPtr pWinStationName;
        public int State;
    }

    public static bool HasActiveRdpSession(string computerName = null)
    {
        if (string.IsNullOrEmpty(computerName))
            computerName = Environment.MachineName;

        IntPtr hServer = computerName.Equals(Environment.MachineName, StringComparison.OrdinalIgnoreCase) 
            ? IntPtr.Zero 
            : WTSOpenServer(computerName);

        IntPtr pSessionInfo = IntPtr.Zero;
        int count = 0;

        try
        {
            if (!WTSEnumerateSessions(hServer, 0, 1, ref pSessionInfo, ref count))
                return false;

            int elementSize = Marshal.SizeOf(typeof(WTS_SESSION_INFO));
            IntPtr currentPtr = pSessionInfo;

            for (int i = 0; i < count; i++)
            {
                WTS_SESSION_INFO session = (WTS_SESSION_INFO)Marshal.PtrToStructure(currentPtr, typeof(WTS_SESSION_INFO));

                if (session.State == 0) // Active
                {
                    IntPtr buffer = IntPtr.Zero;
                    int bytes = 0;

                    if (WTSQuerySessionInformation(hServer, session.SessionId, 16, out buffer, out bytes))
                    {
                        short protocol = Marshal.ReadInt16(buffer);
                        WTSFreeMemory(buffer);

                        if (protocol == 2) // RDP
                        {
                            return true;
                        }
                    }
                }

                currentPtr = IntPtr.Add(currentPtr, elementSize);
            }

            return false;
        }
        finally
        {
            if (pSessionInfo != IntPtr.Zero)
                WTSFreeMemory(pSessionInfo);

            if (hServer != IntPtr.Zero && !computerName.Equals(Environment.MachineName, StringComparison.OrdinalIgnoreCase))
                WTSCloseServer(hServer);
        }
    }
}
